<h1 align="center">Forma√ß√£o Node.js üíª</h1>

<h2 align="center">  
  
  :memo:
  
  Programa√ß√£o Ass√≠ncrona
</h2>

## O que √© programa√ß√£o s√≠ncrona?

A linha de c√≥digo s√≥ vai ser executada quando a anterior finalizar.

```PHP
<? PHP
  checkEmail();
  hashPassword();
  uploadPic();
  saveInfos();
  sendEmail();
?>
```

## O que √© programa√ß√£o ass√≠ncrona?

Os comandos executam independente da ordem de escrita.  
As fun√ß√µes executam ao mesmo tempo sem bloquear o fluxo da aplica√ß√£o,

```js
func1();
func2();
func3();
```

## Op√ß√µes

- Callbacks
- Promise
- Async/Await

## Callbacks

```js
function sendEmail(user, body, callback) {
  setTimeout(() => {
    console.log(`
      Para: ${user}
      ----------------------------------------------------------------
      ${body}
    `);
    callback();
  }, 8000);
  console.log('Email Enviado, chegar√° em breve!');
}

sendEmail('F√°bio', 'Hello Friend!', () => console.log('Fim!'));
```

> "Fim!" ser√° exibido quando ap√≥s o envio do email.

## Par√¢metros em callbacks

```js
function sendEmail(user, body, callback) {
  setTimeout(() => {
    console.log(`
      Para: ${user}
      ----------------------------------------------------------------
      ${body}
    `);
    callback('Enviado', 3000);
  }, 3000);
  console.log('Email Enviado, chegar√° em breve!');
}

sendEmail('F√°bio', 'Hello Friend!', (message, time) => console.log(message, time));
```

## Tratamento de ERROS em Callbacks

```js
function sendEmail(user, body, callback) {
  setTimeout(() => {
    // ...
    const error = true;

    error ? callback('Error ao enviar email') : callback();
  }, 3000);
  console.log('Email Enviado, chegar√° em breve!');
}

sendEmail('F√°bio', 'Hello Friend!', error => console.log(error ? error : 'Sucesso!'));
```

> √â aconselh√°vel colocar o par√¢metro de erro sempre por √∫ltimo.

---

## Promises

S√£o uma evolu√ß√£o dos callbacks, uma forma mais sofisticada de se trabalhar com programa√ß√£o ass√≠ncrona.

Funciona como uma garantia, e garante um sucesso ou uma falha.

```js
function sendEmail(body, user) {
  return new Promise((resolve, reject) => {
    console.log('enviando');
    setTimeout(() => {
      const error = true;
      error ? reject() : resolve();
    }, 3000);
  });
}

sendEmail('Hello Friend', 'F√°bio')
  .then(() => {
    console.log('finalizado');
  })
  .catch(() => {
    console.log('error');
  });
```

> √â necess√°rio tratar as promises com catch, caso aconte√ßa dela ser rejeitada;

## Promises com par√¢metros

S√≥ √© poss√≠vel passar 1 par√¢metro, tanto no Resolve quanto no Reject

```js
function sendEmail(body, user) {
  return new Promise((resolve, reject) => {
    console.log('enviando');
    setTimeout(() => {
      const error = true;
      error ? reject({ message: 'Error' }) : resolve({ time: 3000, to: 'Fulano' });
    }, 3000);
  });
}

sendEmail('Hello Friend', 'F√°bio')
  .then(json => {
    console.log('finalizado', json);
  })
  .catch(error => {
    console.log(error);
  });
```

## Promises aninhadas ou Promise Hell

Quando existe mais l√≥gicas, ter v√°rias promises aninhadas a aplica√ß√£o ficar√° uma bagun√ßa e dif√≠cil de entender.

```js
function catchId() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(5);
    }, 1500);
  });
}

function checkEmail(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('email@gmail.com');
    }, 2000);
  });
}

function sendEmail(body, user) {
  return new Promise((resolve, reject) => {
    console.log('enviando');
    setTimeout(() => {
      const error = true;
      error ? reject({ message: 'Error' }) : resolve({ time: 3000, to: 'Fulano' });
    }, 3000);
  });
}

catchId().then(id => {
  checkEmail(id).then(email => {
    sendEmail('bla bla bla', email)
      .then(() => {
        console.log('Email enviado');
      })
      .catch(err => {
        console.log(err);
      });
  });
});
```

## Async/Await

Para evitar o Promise Hell √© usado o async await.

```js
function catchUsers() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve([
        { name: 'F√°bio', age: 22 },
        { name: 'Jos√©', age: 42 },
        { name: 'Teixeira', age: 32 }
      ]);
    }, [2000]);
  });
}

async function mainFunc() {
  const users = await catchUsers();
  const users2 = await catchUsers();
  const users3 = await catchUsers();
  console.log(users);
}

mainFunc();
```

## Tratamento de erros com Async e Await

```js
function catchUsers() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve([
        { name: 'F√°bio', age: 22 },
        { name: 'Jos√©', age: 42 },
        { name: 'Teixeira', age: 32 }
      ]);
    }, [2000]);
  });
}

async function mainFunc() {
  try {
    const users = await catchUsers();
  } catch (err) {
    console.log(err);
  }
}
```
